POST http://localhost:4004/browse/Holes
Content-Type: application/json

{
  "hole":1,
  "par": 3,
  "score": 5
}

###
GET http://localhost:4004/browse/Holes

###
GET http://localhost:4004/browse/Clubs

###
POST http://localhost:4004/browse/Clubs
Content-Type: application/json

{
      "type": "Iron",
      "value": 9
}

###
POST http://localhost:4004/browse/Clubs
Content-Type: application/json

{
      "value": 9
}